apiVersion: apps/v1
kind: Deployment
metadata:
  name: stminakirchemuenchen-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stminakirchemuenchen-backend
  template:
    metadata:
      name: stminakirchemuenchen-backend
      labels:
        app: stminakirchemuenchen-backend
    spec:
      containers:
        - name: stminakirchemuenchen-backend
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
          ports:
            - name: http
              containerPort: 8080
              hostPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 60
          image: main-server.fritz.box:32000/stminakirchemuenchen-backend